name: testing

on: [ push, pull_request ]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pip-tools
        run: pip install pip-tools

      - name: Set up environment
        run: pip-compile setup.py

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build lib
        run: python setup.py install

      - name: Run tests
        run: python -m unittest discover --verbose
